# tasks file
---
- name: create (download) directory
  file:
    path: "{{ pycharm_downloads_path }}"
    state: directory
    owner: "{{ artifact_owner }}"
    group: "{{ artifact_owner }}"
    mode: 0755
  tags:
    - configuration
    - pycharm
    - pycharm-download

- name: download
  get_url:
    url: "{{ pycharm_download_url }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    owner: "{{ artifact_owner }}"
    group: "{{ artifact_owner }}"
    mode: 0644
  tags:
    - configuration
    - pycharm
    - pycharm-download

- block:

    - name: install | old
      unarchive:
        src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
        dest: "{{ pycharm_install_prefix }}"
        creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_version }}"
        copy: false
      when: pycharm_version is version('2016.1.0', '<')
      tags:
        - pycharm-install-old
      become: true

    - name: install | new
      unarchive:
        src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
        dest: "{{ pycharm_install_prefix }}"
        creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}"
        copy: false
      when: pycharm_version is version('2016.1.0', '>=')
      tags:
        - pycharm-install-new
      become: true

    - name: Create Launcher Entry | new
      template:
        src: jetbrains-pycharm-ce.desktop.j2
        dest: /usr/share/applications/jetbrains-pycharm-ce.desktop
        mode: 0644
        owner: root
        group: root
      when: pycharm_version is version('2016.1.0', '>=')
      tags:
        - pycharm-launcher-new
      become: true

  tags:
    - configuration
    - pycharm
    - pycharm-install
    - pycharm-launcher
